### ISSUE TITLE
cTechstudios has migrated

### ISSUE THREAD

**Issue by dude2093350** [D-Multi-cTech/D-Multi-cTech.github.io#2]
cTechstudios new and improved website is now at dude2093350.github.io/ctech/index.htm not home.html
soon to move to cTechstudios.com and ProjectGo.com

**Comment by dguis** [comment]
I would like to inform you that ProjectGo.com is already owned by Oyvind Neuman.

**Comment by dude2093350** [comment]
Thank you, i am working on a solution, also please update the cTechstudios-D-Multi website so the links go to dude2093350.github.io or dude2093350.github.io/cTech (instead of home.html)

**Comment by dguis** [comment]
Okay.

**Comment by dguis** [comment]
It looks like you already moved your link! The site looks nice by the way.

**Comment by dguis** [comment]
We need to redo the styles of the cTechstudios-D-Multi site. It doen't look so good.
